package com.enablero.todo.dal.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.enablero.todo.model.TodoStatus;
import com.enablero.todo.utlis.LocalDateTimeConverter;
import com.enablero.todo.utlis.TodoStatusConverter;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "todo")
public class Todo {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "title")
    private String title;


    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBTypeConverted(converter = TodoStatusConverter.class)
    @DynamoDBAttribute(attributeName = "status")
    private TodoStatus status;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "createdDt")
    private LocalDateTime createdDt;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "updateDt")
    private LocalDateTime updateDt;

    public void setCreatedDt(LocalDateTime createdDt) {
        this.createdDt = createdDt;
    }

    public Todo() {}

    public String getId() {
        return id;
    }

    public LocalDateTime getCreatedDt() {
        return createdDt;
    }

    public void setUpdateDt(LocalDateTime updateDt) {
        this.updateDt = updateDt;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Todo(String email, String title, String description, TodoStatus status) {
        this.email = email;
        this.title = title;
        this.description = description;
        this.status = status;
        this.createdDt = LocalDateTime.now();
        this.updateDt = LocalDateTime.now();
    }

    public LocalDateTime getUpdateDt() {
        return updateDt;
    }

    public void setUpdateDt() {
        this.updateDt = LocalDateTime.now();
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TodoStatus getStatus() {
        return status;
    }

    public void setStatus(TodoStatus status) {
        this.status = status;
    }

    public void setCreatedDt() {
        this.createdDt = LocalDateTime.now();
    }

    @Override
    public String toString() {
        return "Todo{" +
                "id='" + id + '\'' +
                ", email='" + email + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", status=" + status +
                ", createdDt=" + createdDt +
                ", updateDt=" + updateDt +
                '}';
    }
}