package com.enablero.todo.dal.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

//    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index", attributeName = "email")
    @DynamoDBAttribute(attributeName = "email")
    private String email;

    public void setId(String id) {
        this.id = id;
    }

    public User(String id, String email) {
        this.id = id;
        this.email = email;
    }

    public User() {
    }

    public User(String email) {
        this.email = email;
    }

    public String getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
