#  spring.application.name=todo
spring:
  application:
    name: todo
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          issuer-uri: https://accounts.google.com

aws:
  dynamodb:
    url: http://localhost:8000
    accessKey: anything
    secretKey: anything
    region: ap-south-1
